stages:
  - test
  - build
  - deploy

.d_in_d: &d_in_d
  image: docker:20.10          
  services:
    - docker:20.10-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  

.get_app: &get_app
  before_script:
    - apk update && apk add git bash
    - git clone https://${GIT_LOGIN}:${GIT_PASSWORD}@gitlab.skillbox.ru/nikita_satkanov/devops-basics-final-project.git
    - cd devops-basics-final-project/Final_project

.deploy_app: &deploy_app
  before_script:
    - apt-get update -y && apt-get install -y ansible openssh-client 
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$PRIVATE_VM_KEY" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/timeweb
    - ssh-keyscan -H "$IP_ADDRESS" >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/timeweb
  script:
    - ansible-playbook -i ansible/inventory/$HOST ansible/app_playbook.yml -e "app_version=$APP_VERSION" -vvv
  
  

test_before_build:
  <<: *d_in_d
  stage: test
  <<: *get_app
  script:
    - chmod +x run-tests.sh
    - chmod +x scripts/test_in_docker.sh
    - ./run-tests.sh
  artifacts:
    paths:
      - devops-basics-final-project/Final_project/

build_push_app:
  <<: *d_in_d
  stage: build
  dependencies:
    - test_before_build
  script:
    - cd devops-basics-final-project/Final_project
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build . -t satnik01/skillbox-app:$CI_COMMIT_SHORT_SHA 
    - docker push satnik01/skillbox-app:$CI_COMMIT_SHORT_SHA

linter_ansible:
  stage: test
  image: python:3.9-alpine
  script:
    - pip install ansible-lint
    - ansible-galaxy collection install community.docker
    - ansible-lint ansible/app_playbook.yml 
    - ansible-playbook --syntax-check ansible/app_playbook.yml
  allow_failure: true

test_app:
  stage: deploy
  image: debian:latest
  variables:
    IP_ADDRESS: 158.160.32.56
    APP_VERSION: $CI_COMMIT_SHORT_SHA
    HOST: test_hosts
  <<: *deploy_app
  dependencies:
    - linter_ansible  
  only:
    - master
    - uat
    
prod_deploy:
  stage: deploy
  image: debian:latest
  variables:
    IP_ADDRESS: 158.160.104.70
    APP_VERSION: $CI_COMMIT_SHORT_SHA
    HOST: prod_hosts
  <<: *deploy_app
  when: manual  
  only:
    - master
    