- name: Test app deploy
  hosts: all
  vars:
    app_version: "latest"
    app_name: "skillbox-app"
  become: true

  tasks:

    - name: Log in Docker regestry
      community.docker.docker_login:
        registry: "{{ ci_registry }}"
        username: "{{ ci_registry_user }}"
        password: "{{ ci_registry_password }}"

    - name: Pull Docker image from Gitlab regestry
      community.docker.docker_image:
        name: "{{ ci_registry_image }}:{{ app_version }}"
        source: pull

    - name: systemd unit
      ansible.builtin.template:
        src: "./app-unit.service.j2"
        dest: "/etc/systemd/system/{{ app_name }}.service"
      notify:
        - reload systemd

    - name: Manage a systemd service
      ansible.builtin.systemd:
        name: "{{ app_name }}.service"
        state: started
        enabled: true
        daemon_reload: true

  handlers:
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true